### ISSUE TITLE
Configuration File Template Generator

### ISSUE THREAD

**Issue by ccblazer44** [acgt-tax-consultants/orchard#28]
(From Curtis: This module takes in a link file path [String] and creates an entire configuration file but without the arguments in it. I have done this in a file, https://github.com/acgt-tax-consultants/orchard/blob/master/orchard/modules/_driver.py. That file actually does two things at once, the validation and what you need to do. So you can use that for help or not. Up to you.
So, configuration files are structured the same as link files but it does not have all of the same contents. My method was to remove the differences and keep the similarities.)

>Naming: _config_file_template_generator.py
>Functionality: [TODO][Easy to follow description]
>Exceptions: [TODO][List any exceptions you throw and describe when they get thrown.]

- Input
  - link_file_path.yml [String]

- Creates
  - config_file.yml [File]

**Comment by jakereps** [comment]
Handled by #33
