### ISSUE TITLE
Stop Coveralls Spammed Posts

### ISSUE THREAD

**Issue by i2amroy** [acgt-tax-consultants/orchard#45]
As it is Coveralls posts after every build that fails, so if a person pushes several times without updating the tests yet we end up with logs that look like this:
1/2 commits
Coveralls posting
1/2 commits
Coveralls posting

This can be easily seen in my current PR #43 if you scroll down.

Honestly this seems a little excessive to me; we already can see down at the bottom of the PR that the coveralls check failed (with literally the same number it posted in it's post visible next to the failure message) and if absolutely necessary we can click on "Details" to see more. All the actual posts do is clog up the discussion with multiple duplicate posts that literally give you no information that isn't already displayed at the bottom in the testing section.

**Comment by jakereps** [comment]
Done 👍
