### ISSUE TITLE
Add "generated_path" flag to arguments/optionals in the link file

### ISSUE THREAD

**Issue by i2amroy** [acgt-tax-consultants/orchard#46]
As the title mentions, we need to add some method of flagging input/output arguments/optionals as a generated path for purposes of branching. This would allow branching to rewrite paths that are flagged this way to point to a specific branching directory (static paths to outside resources would not need to be flagged as they remain unchanged) and remove the currently hardcoded infile/outfile values.

The simplest way to approach this seems to just add a flag, but I'm not sure if anyone else has a better idea that might impact their particular modules focused less.

**Comment by jakereps** [comment]
Resolved in #67
