### ISSUE TITLE
Driver Module

### ISSUE THREAD

**Issue by jakereps** [acgt-tax-consultants/orchard#5]
> (From Curtis: This module takes as arguments a link and config file path and then calls the other modules. These modules, in order, are the Configuration File Reader Module, Branching Module, and Luigi File Generator Module. The config file reader expects the config and link file paths and returns data structs [Dictionaries] of those two files. The branching module expects those two data structs [Dictionaries] and returns an updated config file data struct [Dictionary] and, possible, creates a log file and a sub directory.
The Luigi File Generator takes as arguments the link file data struct [Dictionary] and the updated config file data struct [Dictionary] and creates a luigi.py file in the Orchard directory. This module then runs that luigi.py file.
Lastly, this module should handle all, if any, exceptions thrown by the modules it calls and respond accordingly. It should print an error message to the terminal, maybe the exact error thrown, maybe add to it, maybe write your own, I don't care.
Curtis Note: We were thinking about having an optional flag that would either delete or not delete the luigi file after the program is done based on the default functionality we decide.
Naming: _driver.py
Functionality: [TODO][Easy to follow description]
Exceptions: [TODO][List any exceptions you throw and describe when they get thrown.]

- Inputs
  - config_file_path.yml [String]
  - link_file_path.yml [String]
- Outputs
  - .....All of the pipelines modules?

Should Call (in order):
- Configuration File Reader Module
- Branching Module
- Luigi File Generator Module
- Runs Luigi File

**Comment by CurtisRose** [comment]
I have made an example but will need help with the Click app from Jorden.

**Comment by jakereps** [comment]
Done.
